### ISSUE TITLE
When the dataset will be open?

### ISSUE THREAD

**Issue by xmu-xiaoma666** [JizhiziLi/RIM#1]
Hello, thanks for your great job, I would like to know when the dataset will be open?

**Comment by FengMu1995** [comment]
+1 the same question

**Comment by memesoo99** [comment]
Same question. Any plans?

**Comment by JizhiziLi** [comment]
Hi there, thanks for showing interest in our work. The paper is currently under review, the dataset, code and the models will be released after review.
